baseurl = "https://example.com"
defaultContentLanguage = "en"
languageCode = "en"
title = "ğŸŒ± å¤å¤©çš„æµ·é£"
theme = "dream"

[services]
[services.disqus]
shortname = ""
# [services.googleAnalytics]
# ID = ""

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "me/background.jpg"
# backgroundImageDark = ""

author = "Skyler"
#description = "å•Šå•Šå•Šå•Šå•Šå•Šå•Š"
avatar = "http://img.sysummery.top/logo.png"
headerTitle = "ğŸŒ± å¤å¤©çš„æµ·é£"
motto = "æ€€å¿µé‚£äº›ä¸ªè¿‡å»çš„å¤å¤©"

#footerBottomText = "åº•éƒ¨çš„æ–‡æ¡ˆ"
#rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

# email = ""

siteStartYear = 2019

favicon = "http://img.sysummery.top/logo.png"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
stickyNav = false
reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
#collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
# showTableOfContents = true
# showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
reorderShares = ["x", "facebook", "whatsapp"]

# [params.navItems]

# [params.twikoo]
# enabled = true
# envID = ""
# region = ""
# lang = ""

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyyå¹´MMæœˆddæ—¥"
